pipeline {
  agent any

  options {
    disableConcurrentBuilds()
  }

  triggers {
    // every minute
    cron('* * * * *')
  }

  stages {
    stage('Build') {
      steps {
        dir('ansible') {
          ansiColor('xterm') {
            ansiblePlaybook {(
                colorized: true,
                inventory: 'hosts-local',
                playbook: 'Logs/mysql_to_cloudwatch/cloudturf.yml'
              )
            }
          }
        }
      }
    }
  }
}
